---
title: "wonder"
output: html_document
---

```{r}
setwd("D:/UCSB/PSTAT296/Adjusting-Mortality-Curves-for-Rising-Opioid-Related-Deaths/Data")

rm(list=ls())
gc()

library(wondeR)
library(PythonInR)
```

```{r}
df <- get_data(
  ROOTPATH = "D:/UCSB/PSTAT296/Adjusting-Mortality-Curves-for-Rising-Opioid-Related-Deaths/Data", # this should include an "input" and "output" subdirectory
  RUNNAME = "sex_race_overdose", # Name of the run
  replace = T, # Default True, if False then this will not collect data
  pypath = "D:/Python/python.exe", # Path to your python3.exe file (see above)

  ## Collect data on deaths that include these ICD10 codes
  MCD1 = c("T36-T50"), ## Any of these codes...
  MCD2 = c("X40-X44", "X60-X64", "X85", "Y10-Y14"), ## AND any of these codes. Defaults to c(NA), which is All death codes

  ## Segment the data based upon these variables
  by_vars = c("state", "sex", "race") # can be sex, age, race, hispanic, state
)

```

```{r}
mylist <- list(list("Group Results By", "Year"),
               list("And By", "Month"),
               list("And By", "State"))
mydata2 <- getData("Natality for 2007 - 2022", mylist)





```

