---
title: "Modeling"
author: "PSTAT 296A"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
library(mgcv)     
library(plotly)
library()
```

```{r}
df_raw <- read_csv("../data/wonder_opioid/Five-Year-Age-Group.csv", 
                   n_max = 506,
                   show_col_types = FALSE, 
                   na = c("", "NA", "Not Applicable", "Suppressed", 'Unreliable')) %>% 
  clean_names() %>% 
  filter(!is.na(year))  

#names(df_raw)
#glimpse(df_raw)

df_year <- df_raw %>% 
  mutate(
    year = as.integer(year),
    age_groups = five_year_age_groups
  )

# Convert age_groups to numeric age midpoint
df_year <- df_year %>% 
  mutate(
    age_lo = case_when(
      age_groups == "< 1 year" ~ 0,
      TRUE ~ as.numeric(str_extract(age_groups, "^\\d+"))
    ),
    age_hi = case_when(
      age_groups == "< 1 year" ~ 0,
      str_detect(age_groups, "\\+") ~ age_lo + 9,
      TRUE ~ as.numeric(str_extract(age_groups, "(?<=-)\\d+"))
    ),
    age = (age_lo + age_hi) / 2,
    mortality = deaths / population
  ) %>% 
  drop_na(age, deaths)

# Filter ages 20-60
df1 <- df_year %>% 
  filter(age >= 20, age <= 60)

df1 <- df1 %>% 
  mutate(log_rate = log(mortality))

fit <- gam(
  log_rate ~ s(age, k = 4) + s(year, k = 6),
  data = df1,
  method = "REML"
)
```

```{r}
summary(fit)
```


```{r}
# Not 3d
grid <- expand_grid(
  age  = sort(unique(df1$age)),
  year = sort(unique(df1$year))
)

grid$u_hat <- predict(fit, newdata = grid)
grid$y_hat <- exp(grid$u_hat)

grid %>% 
  ggplot(aes(x = age, y = y_hat, group = year)) +
  geom_line(alpha = 0.3) +
  labs(x = "Age", y = "Smoothed log mortality rate")
```

```{r}

yrs_keep <- seq(2003, 2023, by = 1)

pdat <- grid %>%  filter(year %in% yrs_keep)

age_fine <- seq(25, 65, by = 1)

grid_fine <- expand_grid(
  year = yrs_keep,
  age  = age_fine
)

## M_{x,t}
grid_fine$y_hat <- (predict(fit, newdata = grid_fine))


# rows = age, cols = year
mat_u <- grid_fine %>%
  select(age, year, y_hat) %>%
  tidyr::pivot_wider(names_from = year, values_from = y_hat) %>%
  arrange(age)

u_xt <- as.matrix(mat_u %>% select(-age))
rownames(u_xt) <- mat_u$age
colnames(u_xt) <- as.character(sort(yrs_keep))


p <- plot_ly() %>% 
  add_trace(
    data = grid_fine,
    x = ~age, y = ~year, z = ~y_hat,
    type = "scatter3d", mode = "lines",
    split = ~year, line = list(width = 5), opacity = 0.85
) %>% 
  layout(
  title = list(text = "Opioid Mortality Distribution", 
               x = 0.5, 
               y = 0.95),
  scene = list(
        domain = list(x = c(0.1, 1), y = c(0.1, 1)),
        aspectmode = "manual",
        aspectratio = list(x = 1.2, y = 1.2, z = 0.9),
        camera = list(
          eye = list(x = -1.08, y = 1.75, z = 0.35),
          center = list(x = 0, y = 0, z = -0.15),
          up  = list(x = 0, y = 0, z = 1)
                      ),
    uirevision = TRUE,
    domain = list(y = c(0.09, 1)),
    xaxis = list(title = "Age", autorange = "reversed"),
    yaxis = list(title = "Time (Year)", autorange = "reversed"),
    zaxis = list(title = "Smoothed Log Mortality U(x,t)") 
              ),
  legend = list(
    title = list(text = "Year"), 
    orientation = "h", 
    x = 0.5, 
    xanchor = "center", 
    y = 0.08, 
    yanchor = "top", font = list(size = 8), itemsizing = "constant", 
    entrywidth = 20, entrywidthmode = "pixels", tracegroupgap = 0),
  margin = list(b = 0, r = 60, t = 0)
) %>%
  config(
    toImageButtonOptions = list(
      format = "png",
      filename = "opioid_distibution",
      scale = 4
    )
  )

p
```
```{r}
# matrix on spreadsheet
View(u_xt)
```


```{r, fig.width=12, fig.height=9}
zmat <- grid_fine %>% 
  select(year, age, y_hat) %>% 
  pivot_wider(names_from = age, values_from = y_hat) %>% 
  arrange(year)

x_time  <- zmat$year
y_age <- as.numeric(colnames(zmat)[-1])
z      <- as.matrix(zmat %>%  select(-year))

draw_surface <- function(theta = theta, phi = phi, expand = 1) {

  pmat <- persp(
    x = x_time, y = y_age, z = z,
    xlab = "", ylab = "", zlab = "",
    theta = theta, phi = phi, expand = expand,
    shade = 0.4, col = "gray85",
    ltheta = 120, ticktype = "detailed",
    axes = FALSE, box = TRUE
  )

  z0 <- min(z); z1 <- max(z)
  x0 <- min(x_time); x1 <- max(x_time)
  y0 <- min(y_age); y1 <- max(y_age)
  
  tick_len <- 0.05 * (z1 - z0)   # longer tick marks
  
  p1 <- trans3d(min(x_time), max(y_age), z0, pmat)
  p2 <- trans3d(max(x_time), max(y_age), z0, pmat)
  segments(p1$x, p1$y, p2$x, p2$y, lwd = 2)

  time_ticks <- seq(min(x_time), max(x_time), by = 5)
  for (tt in time_ticks) {
    a <- trans3d(tt, max(y_age), z0, pmat)
    b <- trans3d(tt, max(y_age), z0 + tick_len, pmat)
    segments(a$x, a$y, b$x, b$y)
    text(a$x, a$y, tt, pos = 1, cex = 1.0, xpd = NA)
  }

lab_time <- trans3d(mean(x_time), max(y_age), z0, pmat)
text(lab_time$x, lab_time$y, "Time (Year)", font = 2, cex = 1.2, pos = 4)

q1 <- trans3d(max(x_time), min(y_age), z0, pmat)
q2 <- trans3d(max(x_time), max(y_age), z0, pmat)
segments(q1$x, q1$y, q2$x, q2$y, lwd = 2)

  age_ticks <- seq(20, 60, by = 10)
  for (ag in age_ticks) {
    a <- trans3d(max(x_time), ag, z0, pmat)
    b <- trans3d(max(x_time), ag, z0 + tick_len, pmat)
    segments(a$x, a$y, b$x, b$y)
    text(a$x, a$y, ag, pos = 1, cex = 1.0, xpd = NA)
  }

  lab_age <- trans3d(max(x_time), mean(y_age) , z0, pmat)
  text(lab_age$x, lab_age$y, "Age", font = 2, cex = 1.2, pos = 1, xpd = NA)
  
  lab_z <- trans3d(min(x_time), min(y_age), max(z), pmat)
  text(lab_z$x, lab_z$y, "Smoothed Mortality u(x,t)", font = 2, cex = 1.2, pos = 1)
}

draw_surface(theta = 320, phi = 5)
```

```{r}
# read region-level file
df_region_raw <- read_csv(
  "../data/wonder_opioid/Five-Year-Region.csv",
  n_max = 2024,
  show_col_types = FALSE,
  na = c("", "NA", "Not Applicable", "Suppressed", 'Unreliable')
) %>%
  clean_names() %>%
  filter(!is.na(year))

df_region <- df_region_raw %>%
  mutate(
    year = as.integer(year),
    age_groups = five_year_age_groups
  ) %>%
  mutate(
    age_lo = case_when(
      age_groups == "< 1 year" ~ 0,
      TRUE ~ as.numeric(str_extract(age_groups, "^\\d+"))
    ),
    age_hi = case_when(
      age_groups == "< 1 year" ~ 0,
      str_detect(age_groups, "\\+") ~ age_lo + 9,
      TRUE ~ as.numeric(str_extract(age_groups, "(?<=-)\\d+"))
    ),
    age = (age_lo + age_hi) / 2,
    mortality = deaths / population
  ) %>%
  drop_na(age, deaths, population, census_region) %>%
  filter(age >= 20, age <= 60, mortality > 0) %>%
  mutate(log_rate = log(mortality))

yrs_keep <- seq(2003, 2023, by = 1)
age_fine <- seq(25, 65, by = 1)

regions <- sort(unique(df_region$census_region))

region_plots <- list()
region_matrices <- list()

for (reg in regions) {
  
  df_reg <- df_region %>%
    filter(census_region == reg)
  
  fit_reg <- gam(
    log_rate ~ s(age, k = 4) + s(year, k = 6),
    data = df_reg,
    method = "REML"
  )
  
  grid_fine <- expand_grid(
    year = yrs_keep,
    age  = age_fine
  )
  
  grid_fine$u_hat <- predict(fit_reg, newdata = grid_fine)
  grid_fine$y_hat <- exp(grid_fine$u_hat)
  
  # matrix: rows = age, cols = year
  mat_u <- grid_fine %>%
    select(age, year, u_hat) %>%
    pivot_wider(names_from = year, values_from = u_hat) %>%
    arrange(age)
  
  u_xt <- as.matrix(mat_u %>% select(-age))
  rownames(u_xt) <- mat_u$age
  colnames(u_xt) <- as.character(sort(yrs_keep))
  
  region_matrices[[reg]] <- u_xt
  
  
  region_plots[[reg]] <- plot_ly() %>%
    add_trace(
      data = grid_fine,
      x = ~age, y = ~year, z = ~u_hat,
      type = "scatter3d",
      mode = "lines",
      split = ~year,
      line = list(width = 5),
      opacity = 0.85
    ) %>%
    layout(
      title = list(
        text = paste("Opioid Mortality Distribution -", reg),
        x = 0.5,
        y = 0.97
      ),
      scene = list(
        domain = list(x = c(0.1, 1), y = c(0.1, 1)),
        aspectmode = "manual",
        aspectratio = list(x = 1.2, y = 1.2, z = 0.9),
        camera = list(
          eye = list(x = -1.08, y = 1.75, z = 0.35),
          center = list(x = 0, y = 0, z = -0.15),
          up  = list(x = 0, y = 0, z = 1)
        ),
        uirevision = TRUE,
        xaxis = list(title = "Age", autorange = "reversed"),
        yaxis = list(title = "Time (Year)", autorange = "reversed"),
        zaxis = list(title = "Smoothed Log Mortality U(x,t)")
      ),
      legend = list(
        title = list(text = "Year"),
        orientation = "h",
        x = 0.5,
        xanchor = "center",
        y = 0.08,
        yanchor = "top",
        font = list(size = 8),
        itemsizing = "constant",
        entrywidth = 20,
        entrywidthmode = "pixels",
        tracegroupgap = 0
      ),
      margin = list(b = 0, r = 60, t = 0)
    ) %>%
  config(
    toImageButtonOptions = list(
      format = "png",
      filename = paste0("opioid_distribution_", reg),
      scale = 4
    )
  )
}

region_plots[[1]]
region_plots[[2]]
region_plots[[3]]
region_plots[[4]]
```

```{r}
View(region_matrices[[1]])
View(region_matrices[[2]])
View(region_matrices[[3]])
View(region_matrices[[4]])
```

# Convert Monthly opioid death
```{r}
# read region-level file
df_region_raw <- read_csv(
  "../data/wonder_opioid/Five-Year-Region.csv",
  n_max = 2024,
  show_col_types = FALSE,
  na = c("", "NA", "Not Applicable", "Suppressed", 'Unreliable')
) %>%
  clean_names() %>%
  filter(!is.na(year))

df_region <- df_region_raw %>%
  mutate(
    year = as.integer(year),
    age_groups = five_year_age_groups
  ) %>%
  mutate(
    age_lo = case_when(
      age_groups == "< 1 year" ~ 0,
      TRUE ~ as.numeric(str_extract(age_groups, "^\\d+"))
    ),
    age_hi = case_when(
      age_groups == "< 1 year" ~ 0,
      str_detect(age_groups, "\\+") ~ age_lo + 9,
      TRUE ~ as.numeric(str_extract(age_groups, "(?<=-)\\d+"))
    ),
    age = (age_lo + age_hi) / 2,
    mortality = deaths / population
  ) %>%
  drop_na(age, deaths, population, census_region) %>%
  filter(age >= 20, age <= 60, mortality > 0) %>%
  mutate(log_rate = log(mortality))

yrs_keep <- seq(2003, 2020, by = 1/12)
age_fine <- seq(25, 65, by = 1)

regions <- sort(unique(df_region$census_region))

region_plots <- list()
region_matrices <- list()

for (reg in regions) {
  
  df_reg <- df_region %>%
    filter(census_region == reg)
  
  fit_reg <- gam(
    log_rate ~ s(age, k = 4) + s(year, k = 6),
    data = df_reg,
    method = "REML"
  )
  
  grid_fine <- expand_grid(
    year = yrs_keep,
    age  = age_fine
  )
  
  grid_fine$u_hat <- predict(fit_reg, newdata = grid_fine)
  grid_fine$y_hat <- exp(grid_fine$u_hat)
  
  # matrix: rows = age, cols = year
  mat_u <- grid_fine %>%
    select(age, year, u_hat) %>%
    pivot_wider(names_from = year, values_from = u_hat) %>%
    arrange(age)
  
  u_xt <- as.matrix(mat_u %>% select(-age))
  rownames(u_xt) <- mat_u$age
  colnames(u_xt) <- as.character(sort(yrs_keep))
  
  region_matrices[[reg]] <- u_xt
}
```

```{r}
write.csv(region_matrices[[1]], file = "Northeast_opioid_logmxt.csv", row.names = TRUE)
write.csv(region_matrices[[2]], file = "Midwest_opioid_logmxt.csv", row.names = TRUE)
write.csv(region_matrices[[3]], file = "South_opioid_logmxt.csv", row.names = TRUE)
write.csv(region_matrices[[4]], file = "West_opioid_logmxt.csv", row.names = TRUE)
```
