---
title: "Wonder Time Series"
output: html_document
---

```{r message=FALSE}
library(dplyr)
library(ggplot2)
library(stringr)
library(readxl)
library(forecast)
library(lubridate)
library(tseries)
library(strucchange)
library(purrr)
```

## All Deaths

```{r}
year_month <- read.csv("../data/time_series/WONDER-YearMonth.csv") %>%
  filter(Notes != "Total" & Year != "NA") %>%
  mutate(Date = as.Date(paste0(Month.Code, "/01"), format = "%Y/%m/%d"))

plot(year_month$Date, year_month$Deaths, type = "l",
     xlab = "Date", ylab = "# of Deaths", main = "Opioid-Related Death Counts Over Time")
abline(v=as.numeric(as.Date("2014-01-01")), col="red", lty="dotted")
```

```{r}
breakpoints(Deaths ~ Date, data = year_month, breaks = 1)
```

```{r}
pre <- year_month %>% filter(Year < 2014)
post <- year_month %>% filter(Year >= 2014)

acf(diff(pre$Deaths), lag.max = 36)
acf(diff(post$Deaths, differences = 2), lag.max = 36)
```

```{r}
six_month <- year_month %>%
  mutate(group6 = ceiling(row_number() / 6)) %>%
  group_by(group6) %>%
  summarise(
    start_date = first(Date),
    deaths_6mo = sum(Deaths)
  ) %>%
  mutate(
    total_deaths = sum(deaths_6mo),
    lambda_6mo = deaths_6mo / total_deaths,
    fitted_6mo = lambda_6mo * total_deaths
  )

ggplot() +
  geom_line(data = year_month, aes(x = Date, y = Deaths),
            color = "black", size = 1, alpha = 0.8) +
  geom_step(data = six_month, aes(x = start_date, y = fitted_6mo/6),
            color = "blue", size = 0.8) +
  labs(
    title = "Original Monthly Deaths vs 6-Month Fitted Intensity Model",
    y = "Deaths", x = "Date"
  ) +
  theme_minimal()
```

```{r}
twelve_month <- year_month %>%
  mutate(group12 = ceiling(row_number() / 12)) %>%
  group_by(group12) %>%
  summarise(
    start_date = first(Date),
    deaths_12mo = sum(Deaths)
  ) %>%
  mutate(
    total_deaths = sum(deaths_12mo),
    lambda_12mo = deaths_12mo / total_deaths,
    fitted_12mo = lambda_12mo * total_deaths
  )

ggplot() +
  geom_line(data = year_month, aes(x = Date, y = Deaths),
            color = "black", size = 1, alpha = 0.8) +
  geom_step(data = twelve_month, aes(x = start_date, y = fitted_12mo/12),
            color = "red", size = 0.8) +
  labs(
    title = "Fit of Non-homogenous Poisson Modeled Death Counts",
    y = "Deaths", x = "Date") +
  theme_minimal() +
  theme(plot.title = element_text(size = 18),
        axis.title = element_text(size = 12))
```

```{r}
year_month <- year_month %>%
  mutate(mean = NA,
         variance = NA)
```

```{r}
last_ma <- nrow(year_month) - 7

for(i in 7:last_ma){
  
  idx_full <- (i-5):(i+5)
  idx_left  <- i-6            
  idx_right <- i+6
  
  x_vals <- c(year_month$Deaths[idx_full],
              year_month$Deaths[idx_left],
              year_month$Deaths[idx_right])
  
  w_vals <- c(rep(1, 11), 0.5, 0.5)
  
  mu <- weighted.mean(x_vals, w_vals)
  year_month$mean[i] <- mu
  
  year_month$variance[i] <- sum(w_vals^2 * (x_vals - mu)^2) / sum(w_vals^2)
}
```

```{r}
dispersion_set <- year_month %>%
  filter(mean != 'NA') %>%
  mutate(dispersion = variance / mean)

ggplot() +
  geom_line(data = dispersion_set,
            aes(x = Date, y = Deaths, color = "Original"), 
            size = 1, alpha = 0.8) +
  geom_step(data = dispersion_set,
            aes(x = Date, y = mean, color = "13-Month Moving Average"),
            size = 0.8) +
  labs(
    title = "13-Month Moving Average of Opioid Death Counts",
    y = "Deaths", x = "Date",
    color = "Legend") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(size = 18))

plot(dispersion_set$Date, log(dispersion_set$dispersion), type = "l",
     xlab = "Date", ylab = "Log of Dispersion", main = "Test for Over/Underdispersion",
     ylim = c(0,6))
abline(h = log(1), col = "red", lty = 2)

#less than 1 means under-dispersion, more than 1 means over-dispersion
```

## Dispersion Function

```{r}
dispersion_calc <- function(dataset, title) {
  dataset <- dataset %>%
  mutate(mean = NA,
         variance = NA)
  
  last_ma <- nrow(dataset) - 1

  for(i in 2:last_ma){
  
    idx_full <- i
    idx_left  <- i-1            
    idx_right <- i+1
  
    x_vals <- c(dataset$Deaths[idx_full],
                dataset$Deaths[idx_left],
                dataset$Deaths[idx_right])
  
    w_vals <- c(1,0.5,0.5)
  
    mu <- weighted.mean(x_vals, w_vals)
    dataset$mean[i] <- mu
  
    dataset$variance[i] <- sum(w_vals^2 * (x_vals - mu)^2) / sum(w_vals^2)
  }

  dispersion_set <- dataset %>%
    filter(mean != 'NA') %>%
    mutate(dispersion = variance / mean)

  plot(dispersion_set$Year, log(dispersion_set$dispersion), type = "l",
      xlab = "Date", ylab = "Log of Dispersion", main = paste(title, ": Dispersion"),
      ylim = c(-9,9))
  abline(h = log(1), col = "red", lty = 2)
}
```

```{r}
par(mfrow = c(2,2))

ten_year <- read.csv("../data/wonder_opioid/Ten-Year-Age-Group.csv") %>%
  filter(Notes != "Total" & Year != "NA")

ten_25to34 <- ten_year %>%
  filter(Ten.Year.Age.Groups.Code == '25-34') %>%
  mutate(Deaths = as.numeric(Deaths))
dispersion_calc(ten_25to34, "Age Group 25-34")

ten_35to44 <- ten_year %>%
  filter(Ten.Year.Age.Groups.Code == '35-44') %>%
  mutate(Deaths = as.numeric(Deaths))
dispersion_calc(ten_35to44, "Age Group 35-44")

ten_45to54 <- ten_year %>%
  filter(Ten.Year.Age.Groups.Code == '45-54') %>%
  mutate(Deaths = as.numeric(Deaths))
dispersion_calc(ten_45to54, "Age Group 45-54")

ten_55to64 <- ten_year %>%
  filter(Ten.Year.Age.Groups.Code == '55-64') %>%
  mutate(Deaths = as.numeric(Deaths))
dispersion_calc(ten_55to64, "Age Group 55-64")
```

```{r}
par(mfrow = c(2,2))

census_region <- read.csv("../data/wonder_opioid/Census-Region.csv") %>%
  filter(Notes != "Total" & Year != "NA")

region_1 <- census_region %>%
  filter(Census.Region.Code == 'CENS-R1') %>%
  mutate(Deaths = as.numeric(Deaths))
dispersion_calc(region_1, "Northeast Region")

region_2 <- census_region %>%
  filter(Census.Region.Code == 'CENS-R2') %>%
  mutate(Deaths = as.numeric(Deaths))
dispersion_calc(region_2, "Midwest Region")

region_3 <- census_region %>%
  filter(Census.Region.Code == 'CENS-R3') %>%
  mutate(Deaths = as.numeric(Deaths))
dispersion_calc(region_3, "South Region")

region_4 <- census_region %>%
  filter(Census.Region.Code == 'CENS-R4') %>%
  mutate(Deaths = as.numeric(Deaths))
dispersion_calc(region_4, "West Region")
```

## All Causes Of Death

```{r}
year_month <- read.csv("../data/time_series/all-causes.csv") %>%
  filter(Notes != "Total" & Year != "NA") %>%
  mutate(Date = as.Date(paste0(Month.Code, "/01"), format = "%Y/%m/%d"))

year_month <- year_month %>%
  mutate(mean = NA,
         variance = NA)
```

```{r}
last_ma <- nrow(year_month) - 5

for(i in 7:last_ma){
  
  idx_full <- (i-5):(i+5)
  idx_left  <- i-6            
  idx_right <- i+6
  
  x_vals <- c(year_month$Deaths[idx_full],
              year_month$Deaths[idx_left],
              year_month$Deaths[idx_right])
  
  w_vals <- c(rep(1, 11), 0.5, 0.5)
  
  mu <- weighted.mean(x_vals, w_vals)
  year_month$mean[i] <- mu
  
  year_month$variance[i] <- sum(w_vals^2 * (x_vals - mu)^2) / sum(w_vals^2)
}
```

```{r}
dispersion_set <- year_month %>%
  filter(mean != 'NA') %>%
  mutate(dispersion = variance / mean)

ggplot() +
  geom_line(data = dispersion_set,
            aes(x = Date, y = Deaths, color = "Original"), 
            size = 1, alpha = 0.8) +
  geom_step(data = dispersion_set,
            aes(x = Date, y = mean, color = "13-Month Moving Average"),
            size = 0.8) +
  labs(
    title = "13-Month Moving Average of US Death Counts",
    y = "Deaths", x = "Date",
    color = "Legend") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(size = 18))

plot(dispersion_set$Date, log(dispersion_set$dispersion), type = "l",
     xlab = "Date", ylab = "Log of Dispersion", main = "Test for Over/Underdispersion",
     ylim = c(0,10))
abline(h = log(1), col = "red", lty = 2)

#less than 1 means under-dispersion, more than 1 means over-dispersion
```

```{r}
x <- ts(year_month, start=c(1999,1), end=c(2020,12), frequency=12)
m <- decompose(x)
plot(m$seasonal)
```

## Isotonic Regression Plot

```{r}
iso <- read.csv("../data/time_series/single-year-region.csv") %>%
  filter(Deaths != "NA" & Census.Region.Code == "CENS-R4" & Population != "Not Applicable")

x <- as.numeric(iso$Single.Year.Ages.Code)
y <- as.numeric(iso$Crude.Rate)

# Focus on ages 25-45
main_idx <- x >= 25 & x <= 45
x_main <- x[main_idx]
y_main <- y[main_idx]

# Compute running maximum
running_max <- cummax(y_main)

# Flag points below running max (non-monotonic)
non_monotonic <- y_main < running_max

# Initialize
segments_start <- 1
in_segment <- non_monotonic[1]

# Plot the base line (main curve)
plot(x_main, y_main, type="n",
     xlab = "Age",
     ylab = "Crude Rate (Deaths per 100k)",
     main = "Crude Rate by Age in Region 4 (West)")

# Loop to draw segments
for(i in 2:length(x_main)){
  if(non_monotonic[i] == in_segment){
    # Continue current segment
    next
  } else {
    # Segment change: draw previous segment
    if(in_segment){
      # highlight entire segment in red
      lines(x_main[segments_start:(i-1)], y_main[segments_start:(i-1)], col="red", lwd=3)
    } else {
      # normal segment in black
      lines(x_main[segments_start:(i-1)], y_main[segments_start:(i-1)], col="black", lwd=2)
    }
    # Start new segment
    segments_start <- i-1
    in_segment <- non_monotonic[i]
  }
}

# Draw last segment
if(in_segment){
  lines(x_main[segments_start:length(x_main)], y_main[segments_start:length(x_main)], col="red", lwd=3)
} else {
  lines(x_main[segments_start:length(x_main)], y_main[segments_start:length(x_main)], col="black", lwd=2)
}
```